### ISSUE TITLE
Build failing on Centos 7.1

### ISSUE THREAD

**Issue by wstrange** [mingfang/docker-kubernetes-master#1]
Running Centos 7.1, Docker 1.7.1 

I am using the overlayfs storage driver.

I get:

./build 
Sending build context to Docker daemon 28.16 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:14.04
 ---> 91e54dfb1179
Step 1 : ENV DEBIAN_FRONTEND noninteractive
mkdir /var/lib/docker/overlay/3832caa14c1dbea3b36f7a7c4707f968ead7cb90d98d548a4a1da28d1ee2138d-init/merged/dev/shm: invalid argument

Any ideas?

**Comment by mingfang** [comment]
This looks like a Docker issue 
https://github.com/docker/docker/issues/10294

FWIW I'm on Ubuntu 14.04 and Docker 1.8.1.

**Comment by wstrange** [comment]
Ahh OK - thanks. I will watch that bug. 

Feel free to close this issue if you want.
